# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_number', models.IntegerField()),
                ('current_capacity', models.IntegerField(default=0)),
                ('rated_capacity', models.IntegerField()),
            ],
        ),
    ]
