# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170319_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='libname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
