# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170319_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
