# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_floor_num_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
